spring:
  config:
    activate:
      on-profile: local
    import:
      - ssup-security/application.yml
      - ssup-security/application-datasource.yml
      - ssup-security/application-cloud.yml
      - ssup-security/application-auth.yml

---

spring:
  config:
    activate:
      on-profile: prod
    import:
      - ssup-security/application.yml
      - ssup-security/application-datasource.yml
      - ssup-security/application-cloud.yml
      - ssup-security/application-auth.yml