name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.SUBMODULE_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot JAR
        working-directory: backend
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Build Docker image (amd64)
        working-directory: backend
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t ssup-backend:latest --load .

      - name: Save image to tar
        run: docker save ssup-backend:latest -o backend.tar
      
      - name: Fix permissoions
        run: chmod 644 backend.tar

      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "./backend.tar"
          target: "/home/ec2-user/"

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop app || true
            docker rm app || true
            docker load -i backend.tar
            docker run -d \
              --name app \
              -p 8080:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              ssup-backend:latest

